require 'decogator/advice/bound_around'
require 'decogator/advice/bound_tap'
require 'decogator/advice/after'
require 'decogator/advice/around'
require 'decogator/advice/before'
require 'decogator/advice/tap'
require 'decogator/advice/chain'
require 'decogator/advice/bound_chain'
